// <auto-generated />
using System;
using DotNetCoreWebApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetCoreWebApi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20201226122538_SalesMainTable_And_Item_Table")]
    partial class SalesMainTable_And_Item_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetCoreWebApi.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemName")
                        .HasColumnType("varchar(50)");

                    b.Property<double>("ItemRate");

                    b.HasKey("ItemID");

                    b.ToTable("items");
                });

            modelBuilder.Entity("DotNetCoreWebApi.Models.SalesMain", b =>
                {
                    b.Property<int>("SalesMainID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("SalesDate");

                    b.Property<double>("TotalAmount");

                    b.HasKey("SalesMainID");

                    b.ToTable("SalesMains");
                });
#pragma warning restore 612, 618
        }
    }
}
