// <auto-generated />
using System;
using DotNetCoreWebApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetCoreWebApi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetCoreWebApi.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemName")
                        .HasColumnType("varchar(50)");

                    b.Property<double>("ItemRate");

                    b.HasKey("ItemID");

                    b.ToTable("items");
                });

            modelBuilder.Entity("DotNetCoreWebApi.Models.SalesMain", b =>
                {
                    b.Property<int>("SalesMainID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("SalesDate");

                    b.Property<double>("TotalAmount");

                    b.HasKey("SalesMainID");

                    b.ToTable("SalesMains");
                });

            modelBuilder.Entity("DotNetCoreWebApi.Models.SalesSub", b =>
                {
                    b.Property<int>("SalesSubID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemID");

                    b.Property<int>("ItemQuantity");

                    b.Property<int>("SalesMainID");

                    b.Property<double>("TotalPrice");

                    b.HasKey("SalesSubID");

                    b.HasIndex("ItemID");

                    b.HasIndex("SalesMainID");

                    b.ToTable("SalesSubs");
                });

            modelBuilder.Entity("DotNetCoreWebApi.Models.SalesSub", b =>
                {
                    b.HasOne("DotNetCoreWebApi.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DotNetCoreWebApi.Models.SalesMain", "salesMain")
                        .WithMany("SalesItems")
                        .HasForeignKey("SalesMainID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
